WoEN 18742 air into the deep v0.0
WoEN239/IntoTheDeep18742 pull request #1
Opened 2024-10-16 15:43 UTC by tikhonsmovzh

Написана одометрия на одометрах, удержание скорости, постройка рр траектории в потоках, определение палок.

Из инструментов:  класс пида, евенты, телеметрия, таймеры классы едениц измерения, мягкая серва, класс просто мотора, просто инкодера.

2024-10-16 21:40 UTC, oaleksander requested changes
Мне понравилось, это были плодотворные 4 часа за чтением чужого кода. Большинство косяков - небольшие по структуре/зависимостям или мысли по новому функционалу. 

Больше всего вопросов пока к `RoadRunner.kt` - оно и понятно, это самая важная часть автонома. Хочется по-максимуму воспользоваться возможностями `roadrunner.core` и при этом оставить себе максимально удобный и гибкий интерфейс. Это до мы ещё до конечного автомата стратегии не дошли. 

P.S. Думаю, следующие PR будут поменьше и попроще, может быть по веткам людей будем раскидывать.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/updateListener/UpdateHandler.kt
> +    }
Нехорошо, что в таком, казалось бы, абстрактном интерфейсе есть зависимость от очень конкретной батареи. Я так понял, задача состоит в пробросе зависимостей, которые ещё `null` на момент вызова конструктора. Можно вот что:

1.  Вынести контекст для инициализации в отдельный класс и пробрасывать уже его - вроде `class InitContext(val Battery, val ... )`
2. ~~Заменить Battery на Object и проверять тип в рантайме~~ у нас тут не Java, проверять такое в рантайме это кринж
3. А правда нельзя в конструкторе `Battery` прокинуть? Я вот вижу что в `Motor` в конструкторе `DcMotorEx`, а это зависимость такого же уровня...

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/units/Vec2.kt
> +        val currentRot = atan2(y, x)
Получение угла вектора - очень полезная штука. Надо вынести в публичный метод.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/timer/Timer.kt
> +    private var _isActive = false
Некорректно называть это состоянием, так как оно задается только в начале жизненного цикла. Правильнее обозвать это **типом** - `TimerType` с значениями `DEFAULT`/`SUPPLIER`/`SUPPLIER_TIMEOUT`. И _isActive можно под ту же гребенку - сделать тип по умолчанию `INACTIVE`.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/timer/Timer.kt
> +    }
Можно уменьшить вложенность ветвлений и сделать из этого один красивый `switch-case` в зависимости от **типа** таймера)

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/telemetry/StaticTelemetry.kt
> +    }
Делать обертки над внешними библиотеками с более удобным интерфейсом - крутая тема

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/softServo/SoftServo.kt
> +) : IHandler {
Крутая штука! Хорошо бы добавить ещё обертку над серваком, которая в `setPosition` конвертирует непонятные проценты в человеческие `AngleUnit`. А то ограничения в непонятных попугаях задаются. Можно не сюда, а на уровень ниже и передавать в конструкторе вместо `robotcore.hardware.Servo`.

Кстати, в RoadRunner используются буквально такие же формулы, только в более сложной форме и для 3-х координат.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/pidRegulator/PIDRegulator.kt
> +        val uI = _integral * config.i
Почему-то тут сначала ограничение, а потом умножение. Тогда `limitI` задается не в известных единицах `[u]`, а в `[u / ki]`. Вам реально так удобнее? Ещё, если изменить `ki` то и максимальное значение `uI` внезапо уплывает.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/motor/Motor.kt
> +    val maxVelocityTicks = 2400.0
Такое ~~надо передавать в конструкторе~~ можно вообще не передавать отдельно так как эта штука равна `1/kF`.

P.S. Я помню, что у нас непонятки с тем, как работает setPower и как он зависит от батареи. У меня есть кое-какие данные...

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/exponentialFilter/ExponentialFilter.kt
> +}
Это можно приспособить для того, что бы фильтровать шумы с одного датчика. Достаточно добавить глобальное состояние `state` и метод `filter(target)` в котором будет `state = updateRaw(state, target-state); return state`. Для датчиков расстояния / цвета самое то. Можно даже для плавного изменения положения сервопривода использовать :)

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/gyro/Gyro.kt
> +            if (_iterations > Configs.GyroscopeConfig.GYRO_ITERATIONS) {
Правильнее делать не по количеству итераций, а по времени - вроде бы BNO055 не умеет выдавать значения чаще 100Гц. Можно смело взять, например, 50Гц.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/gyro/Gyro.kt
> +    override fun update() {
Умные люди писали, что можно вынести опрос гироскопа в отдельный поток (с ограничением на временной интервал считывания!). Не могу точно сказать, почему это может увеличить производительность, но, скорее всего, пока рев ждет от I2C-шины данные после запроса гироскопа, можно успеть вклиниться из другого потока, что бы пообщаться с другими устройствами.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/gyro/Gyro.kt
> +    private val _mergeFilter = ExponentialFilter(Configs.GyroscopeConfig.MERGE_COEF)
По-хорошему надо разнести обертку над гироскопом (с ограничением частоты считывания) и его соединение с другим датчиком в разные классы - по аналогии с одометрией `GyroAngle` и `MergeAngle`

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/RoadRunner.kt
> +        if (if (currentTrajectory is TimeTrajectory) _trajectoryTime.seconds() > currentTrajectory.duration else if (currentTrajectory is Action) currentTrajectory.isEnd() else false) {
Нечитаемо( уменьшить вложенность, например, записав условие в локальную переменную

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/RoadRunner.kt
> +            else if (currentTrajectory is Action) currentTrajectory.turnVelocity(_trajectoryTime.seconds()) else 0.0
Надо научиться принимать TimeTurn для полного счастья

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/RoadRunner.kt
> +        val currentTrajectory = _currentTrajectory[0]
Смысл понятен, но выглядит опасно. Как минимум - надо нормально отрабатывать случай, если попался неправильный тип - на 48 строке изменить условие что бы он пропускал неправильное действие. Как максимум - переписать всё на [sealed](https://developer.alexanderklimov.ru/android/kotlin/sealed.php)...

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/Actions.kt
> +}
Надо всё же сделать это через `roadrunner.TimeTurn`, который генерит нормальную функцию угла от времени, а не её имитацию через вложенный ПИД.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/Actions.kt
> +}
Мне нравится, что через этот интерфейс можно подсунуть любой объект в траекторию

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/RoadRunner.kt
> +    }
**Это-потенциальный источник задержек запуска автонома.** Обязательно должна быть возможность сначала построить траекторию (в ините или до запуска опмода вообще, сохранив экземпляр траектории в статику), а при старте незамедлительно начать по ней ехать. С другой стороны, этот инструмент пригодится если нужно срочно достроить неизвестную заранее траекторию в **run**-тайме. Но всё же 99% генережки должно происходить в **init**-тайме.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/RoadRunner.kt
> +            )
Создавать новый `TrajectoryBuilder` под каждый проезд - так себе затея. Всё дело в начальной и конечной скорости - она **нулевая для траектории, но может быть ненулевой - для сегмента траектории**. Представь себе сплайн, сразу после идет которого идет прямой проезд в том же направлении. `TrajectoryBuilder` сможет сшить это в один непрерывный проезд посередине. Если же для сплайна и проезда вперед создать два разных  `TrajectoryBuilder`а, то придется без нужды затормозить посредине.

Скорее всего, придется переработать `ThreadedTrajectoryBuilder`, что бы он вместо кусков траектории принимал уже заготовленные пользователем `TrajectoryBuilder` + штука для `turnTo` и выплевывал массив из `TimeTrajectory`/`TimeTurn`/`Action`, который пользователь сам запустит, когда надо.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/gamepad/Gamepad.kt
> +        if(_gamepad.dpad_down && !_clampOld)
Функционал переключалки значения (`bool` `true`<->`false` или `enum` по очереди через `values` и `ordinal`) по кнопке можно вынести в отдельный класс. Это универсальная штука на все времена

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/motor/MotorOnly.kt
> +class MotorOnly(private val _motor: DcMotorEx): DcMotorEx {
Вместо того, что бы наследовать `DcMotorEx` можно реализовать более слабый `DcMotor`, так придется писать меньше методов-заглушек. Вообще есть `DcMotorSimple`, но там даже `ZeroPowerBehavior` нет

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/motor/EncoderFix.kt
> +        }
Получается, что скорость обновляется раз в аж в 85(!!!) миллисекунд. `velocity` необходимо обновлять постоянно, а вот `mathSpeed` - с ограничением на время.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/devices/Devices.kt
> +}
Можно добавить ограничение на время считывания (заряд же не обновляется каждую миллисекунду?) и добавить фильтрацию через `ExponentialFilter`.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/driveTrain/DriveTrain.kt
> +    }
Выставить таргеты в 0, сбросить пиды (мало ли там I накопилась)

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/RoadRunner.kt
> +            if (_currentTrajectory.isEmpty())
Тут стоит остановиться - мало ли мы потеряли конец траектории и нам не выставили скорость в 0

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/camera/StickProcessor.kt
> +        val hsvFrame = frame.clone()
Возможно, стоит все "локальные" фреймы вынести на уровень класса. Так мы точно не будем насиловать память, выделяя и удаляя большие картинки каждый вызов `processFrame`.

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/linearOpModes/LinearOpModeBase.kt
> +                OpModeManagerImpl.getOpModeManagerOfActivity(AppUtil.getInstance().getActivity()).startActiveOpMode()
Как же я люблю ломать стандартые процедуры

2024-10-16 21:40 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/odometry/OdometersOdometry.kt
> +            _sideOdometer.velocity - Configs.OdometryConfig.SIDE_ODOMETER_RADIUS * Gyro.velocity
Вместо `Gyro.velocity` воткнуть `calculateRotateVelocity()` - не нужно тянуть лишние зависимости + так значение скорости точно будет из того же промежутка времени (ну, из одного пакета).

2024-10-17 05:13 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/updateListener/UpdateHandler.kt
> +    }
Nullом он не может быть, на это говорит Котлин, но проблему с неуместной зависимостью я исправлю

2024-10-17 05:17 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/camera/StickProcessor.kt
> +        val hsvFrame = frame.clone()
Но проблема с клонированием останется, мне нельзя вносить изменения в глобальный кадр, потому что он идёт в другие процессоры которые из-за этого ломаются

2024-10-17 05:32 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/softServo/SoftServo.kt
> +) : IHandler {
Обёртку можно сделать как с MotorOnly чтобы была функция для сета в попугаях, а была в угле

2024-10-17 05:34 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/pidRegulator/PIDRegulator.kt
> +        val uI = _integral * config.i
Я предполагал что ki меньше 1, а это значит что uI меньше limitI, но я понял проблему и исправлю

2024-10-17 05:37 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/exponentialFilter/ExponentialFilter.kt
> +}
Я особо не разбирался с фильмами, но потенциал у них большой

2024-10-17 05:39 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/gyro/Gyro.kt
> +    override fun update() {
Я б сказал что это очень будет странно, т.к хардваир один

2024-10-17 05:41 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/runner/RoadRunner.kt
> +            else if (currentTrajectory is Action) currentTrajectory.turnVelocity(_trajectoryTime.seconds()) else 0.0
Есть такое, но свои функции тоже нужны

2024-10-17 05:51 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/gamepad/Gamepad.kt
> +        if(_gamepad.dpad_down && !_clampOld)
К этому я не причастен

2024-10-17 05:52 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/motor/MotorOnly.kt
> +class MotorOnly(private val _motor: DcMotorEx): DcMotorEx {
Но DcMotorEx более уневерсальный

2024-10-17 05:54 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/devices/Devices.kt
> +}
Ну у тетрикс акумов из-за их старости во время самой простой езды идёт посадка минимум на 2 вольта

2024-10-17 05:58 UTC, tikhonsmovzh commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/odometry/OdometersOdometry.kt
> +            _sideOdometer.velocity - Configs.OdometryConfig.SIDE_ODOMETER_RADIUS * Gyro.velocity
Мне не нравится что будет обращение к хардваирным одометрам из нескольких мест, для фикса этого можно выделить класс для опрашивания одометров, но может выйти проблема с тем что опрос будет после вычисления

2024-10-17 05:59 UTC, tikhonsmovzh commented
Вечером как домой приеду все исправлю

2024-10-17 20:45 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/camera/StickProcessor.kt
> +        val hsvFrame = frame.clone()
Я и не предлагаю менять глобаьльный кадр. Я лишь предлагаю вынести большие объекты за скобки. Вместо:
```kotlin
fun process(frame: Mat) {
    val veryBigObject = frame.clone()
    doTheThing(veryBigObject)
}
```
Сделать:
```kotlin
val veryBigObject = Mat()
fun process(frame: Mat) {
    frame.copyTo(veryBigObject)
    doTheThing(veryBigObject)
}
```
В чем разница? В первом варианте каждый раз, когда мы вызывают `process`, программе приходится выделять большой участок памяти под `veryBigObject`, что бы потом на выходе освободить его.
Во втором варианте у нас лежит выделенный кусок памяти под `veryBigObject` на протяжении всего жизненного цикла. Обрати внимание, что копирование идет через `copyTo`, а не `clone`. Так мы копируем контент кадра в уже выделенную память, а не выделяем новый объект.

2024-10-17 20:51 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/odometry/OdometersOdometry.kt
> +            _sideOdometer.velocity - Configs.OdometryConfig.SIDE_ODOMETER_RADIUS * Gyro.velocity
Разделить процедуры обращения к железу и обработку данных - всегда хорошо. Если заранее позаботиться о том, что бы сначала прочитать все датчики, а потом обрабатывать их из кэша, то потом будет проще, например, удвоить производительность сделав отдельный поток для CH и USB ExH.
У нас нет такого понятия, как "до" или "после" вычисления). Всё крутится в цикле без начала и конца. Разница во времени не настолько существенная, что бы за ней гнаться.

2024-10-17 21:24 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/devices/Devices.kt
> +}
Ну может не раз в секунду. Но уж точно не каждый цикл. Надо расставить приоритеты)

2024-10-17 21:25 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/gyro/Gyro.kt
> +    override fun update() {
Может и не стоит пока так заморачиваться. Кстати, не вижу нигде настроенных [BulkCachingMode](https://gm0.org/en/latest/docs/software/tutorials/bulk-reads.html) для ускореного считывания энкодеров?

2024-10-19 15:50 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/navigation/odometry/MergeOdometry.kt
> +}
Это просто обертка над `OdometersOdometry`, а всем Merge по факту занимается дочерний класс. Надо убрать Merge из `OdometersOdometry`, а тут уже делать расчеты и корректировать `OdometersOdometry` (через сеттер позиции, видимо).

2024-10-23 15:20 UTC, W9sty commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/mainControl/gamepad/Gamepad.kt
> +        if(_gamepad.dpad_down && !_clampOld)
ясно

2024-10-26 08:55 UTC, oaleksander commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/pidRegulator/PIDRegulator.kt
> +        val uI = _integral * config.i
```kotlin
_integral = clamp(_integral, -config.limitI / config.limitI, config.limitI / config.limitI)
```
x / x = 1 :)

2024-10-26 09:26 UTC, oaleksander commented
TODO на будущее:

1. Roadrunner: Всё что с ним связано
2. MergeOdometry: камера
3. Telemetry: Класс для телеметрии с возможностью фильтрации/отключения
4. Gamepad: Сделать отдельный класс для переключения значений по кнопке 
5. Drivetrain: Раскомментить пид (?)
6. Intake: добавить возможность конфигурации позиции через Dashboard
7. Intake: разобраться с 360 серваком. Концевики
8. Intake+Lift: надо как-то автоматизировать. Пока не знаю как, но как-то надо

2024-10-26 09:33 UTC, oaleksander submitted a review, later dismissed

2024-10-26 09:51 UTC, oaleksander approved these changes

2024-10-26 09:52 UTC, merged